/*
Automated Temporary Permissions Process 
Sharon Reid
sharon.reid.harris@gmail.com
https://github.com/InfoJunkie1/TempPerms.git
*/

CREATE DATABASE [PostItReplacement]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PostItReplacement', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\PostItReplacement.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PostItReplacement_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\PostItReplacement_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [PostItReplacement] SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE [PostItReplacement] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PostItReplacement] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PostItReplacement] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PostItReplacement] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PostItReplacement] SET ARITHABORT OFF 
GO
ALTER DATABASE [PostItReplacement] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PostItReplacement] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PostItReplacement] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [PostItReplacement] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PostItReplacement] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PostItReplacement] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PostItReplacement] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PostItReplacement] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PostItReplacement] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PostItReplacement] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PostItReplacement] SET  DISABLE_BROKER 
GO
ALTER DATABASE [PostItReplacement] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PostItReplacement] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PostItReplacement] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PostItReplacement] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PostItReplacement] SET  READ_WRITE 
GO
ALTER DATABASE [PostItReplacement] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [PostItReplacement] SET  MULTI_USER 
GO
ALTER DATABASE [PostItReplacement] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PostItReplacement] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PostItReplacement] SET DELAYED_DURABILITY = DISABLED 
GO
USE [PostItReplacement]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [PostItReplacement]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [PostItReplacement] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
